#############################################################################
# Makefile for building: MyDfsServer
# Generated by qmake (3.0) (Qt 5.4.2)
# Project:  MyDfsServer.pro
# Template: app
# Command: C:\usr\local\QT\5.4\msvc2013_64\bin\qmake.exe -o Makefile MyDfsServer.pro
#############################################################################

MAKEFILE      = Makefile

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = C:\usr\local\QT\5.4\msvc2013_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = copy /y
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: MyDfsServer.pro ..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\win32-msvc2013\qmake.conf ..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\spec_pre.prf \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\common\shell-win32.conf \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\qconfig.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_axbase.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_axbase_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_axcontainer.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_axcontainer_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_axserver.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_axserver_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_bluetooth.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_bluetooth_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_bootstrap_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_clucene_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_concurrent.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_concurrent_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_core.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_core_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_dbus.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_dbus_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_declarative.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_declarative_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_designer.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_designer_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_designercomponents_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_enginio.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_enginio_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_gui.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_gui_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_help.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_help_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_location.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_location_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_multimedia.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_multimedia_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_multimediawidgets.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_network.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_network_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_nfc.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_nfc_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_opengl.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_opengl_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_openglextensions.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_openglextensions_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_platformsupport_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_positioning.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_positioning_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_printsupport.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_printsupport_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_qml.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_qml_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_qmltest.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_qmltest_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_quick.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_quick_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_quickparticles_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_quickwidgets.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_script.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_script_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_scripttools.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_scripttools_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_sensors.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_sensors_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_serialport.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_serialport_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_sql.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_sql_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_svg.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_svg_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_testlib.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_testlib_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_uitools.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_uitools_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_webchannel.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_webchannel_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_webengine.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_webengine_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_webenginecore.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_webenginecore_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_webenginewidgets.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_webkit.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_webkit_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_webkitwidgets.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_webkitwidgets_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_websockets.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_websockets_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_webview.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_webview_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_widgets.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_widgets_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_winextras.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_winextras_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_xml.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_xml_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_xmlpatterns.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\qt_functions.prf \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\qt_config.prf \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\win32\qt_config.prf \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\win32-msvc2013\qmake.conf \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\spec_post.prf \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\exclusive_builds.prf \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\default_pre.prf \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\win32\default_pre.prf \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\resolve_config.prf \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\exclusive_builds_post.prf \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\default_post.prf \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\win32\rtti.prf \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\precompile_header.prf \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\warn_on.prf \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\qt.prf \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\resources.prf \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\moc.prf \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\win32\opengl.prf \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\uic.prf \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\win32\windows.prf \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\testcase_targets.prf \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\exceptions.prf \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\yacc.prf \
		..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\lex.prf \
		MyDfsServer.pro \
		C:/usr/local/QT/5.4/msvc2013_64/lib/qtmain.prl \
		C:/usr/local/QT/5.4/msvc2013_64/lib/Qt5Core.prl \
		C:/usr/local/QT/5.4/msvc2013_64/lib/Qt5Widgets.prl \
		C:/usr/local/QT/5.4/msvc2013_64/lib/Qt5Gui.prl \
		C:/usr/local/QT/5.4/msvc2013_64/lib/Qt5Network.prl
	$(QMAKE) -o Makefile MyDfsServer.pro
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\spec_pre.prf:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\common\shell-win32.conf:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\qconfig.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_axbase.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_axbase_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_axcontainer.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_axcontainer_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_axserver.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_axserver_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_bluetooth.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_bluetooth_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_bootstrap_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_clucene_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_concurrent.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_concurrent_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_core.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_core_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_dbus.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_dbus_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_declarative.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_declarative_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_designer.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_designer_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_designercomponents_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_enginio.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_enginio_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_gui.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_gui_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_help.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_help_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_location.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_location_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_multimedia.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_multimedia_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_network.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_network_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_nfc.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_nfc_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_opengl.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_opengl_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_openglextensions.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_openglextensions_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_platformsupport_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_positioning.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_positioning_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_printsupport.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_printsupport_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_qml.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_qml_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_qmldevtools_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_qmltest.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_qmltest_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_quick.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_quick_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_quickparticles_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_quickwidgets.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_quickwidgets_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_script.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_script_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_scripttools.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_scripttools_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_sensors.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_sensors_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_serialport.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_serialport_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_sql.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_sql_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_svg.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_svg_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_testlib.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_testlib_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_uitools.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_uitools_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_webchannel.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_webchannel_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_webengine.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_webengine_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_webenginecore.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_webenginecore_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_webenginewidgets.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_webenginewidgets_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_webkit.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_webkit_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_webkitwidgets.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_webkitwidgets_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_websockets.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_websockets_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_webview.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_webview_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_widgets.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_widgets_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_winextras.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_winextras_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_xml.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_xml_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_xmlpatterns.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\qt_functions.prf:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\qt_config.prf:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\win32\qt_config.prf:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\win32-msvc2013\qmake.conf:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\spec_post.prf:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\exclusive_builds.prf:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\default_pre.prf:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\win32\default_pre.prf:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\resolve_config.prf:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\exclusive_builds_post.prf:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\default_post.prf:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\win32\rtti.prf:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\precompile_header.prf:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\warn_on.prf:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\qt.prf:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\resources.prf:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\moc.prf:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\win32\opengl.prf:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\uic.prf:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\win32\windows.prf:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\testcase_targets.prf:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\exceptions.prf:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\yacc.prf:
..\..\..\usr\local\QT\5.4\msvc2013_64\mkspecs\features\lex.prf:
MyDfsServer.pro:
C:/usr/local/QT/5.4/msvc2013_64/lib/qtmain.prl:
C:/usr/local/QT/5.4/msvc2013_64/lib/Qt5Core.prl:
C:/usr/local/QT/5.4/msvc2013_64/lib/Qt5Widgets.prl:
C:/usr/local/QT/5.4/msvc2013_64/lib/Qt5Gui.prl:
C:/usr/local/QT/5.4/msvc2013_64/lib/Qt5Network.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile MyDfsServer.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first FORCE
all: release-all debug-all FORCE
clean: release-clean debug-clean FORCE
	-$(DEL_FILE) MyDfsServer.exp
distclean: release-distclean debug-distclean FORCE
	-$(DEL_FILE) Makefile

release-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
